//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("OAuthModel", "Client_ClientAuthorization", "oauth_client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(nOAuth.AuthorizationServer.Infrastructure.oauth_client), "oauth_clientauthorization", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nOAuth.AuthorizationServer.Infrastructure.oauth_clientauthorization), true)]
[assembly: EdmRelationshipAttribute("OAuthModel", "User_ClientAuthorization", "sys_user", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(nOAuth.AuthorizationServer.Infrastructure.sys_user), "oauth_clientauthorization", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nOAuth.AuthorizationServer.Infrastructure.oauth_clientauthorization), true)]

#endregion

namespace nOAuth.AuthorizationServer.Infrastructure
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class OAuthEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“OAuthEntities”部分中的连接字符串初始化新 OAuthEntities 对象。
        /// </summary>
        public OAuthEntities() : base("name=OAuthEntities", "OAuthEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OAuthEntities 对象。
        /// </summary>
        public OAuthEntities(string connectionString) : base(connectionString, "OAuthEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 OAuthEntities 对象。
        /// </summary>
        public OAuthEntities(EntityConnection connection) : base(connection, "OAuthEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<oauth_client> oauth_client
        {
            get
            {
                if ((_oauth_client == null))
                {
                    _oauth_client = base.CreateObjectSet<oauth_client>("oauth_client");
                }
                return _oauth_client;
            }
        }
        private ObjectSet<oauth_client> _oauth_client;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<oauth_clientauthorization> oauth_clientauthorization
        {
            get
            {
                if ((_oauth_clientauthorization == null))
                {
                    _oauth_clientauthorization = base.CreateObjectSet<oauth_clientauthorization>("oauth_clientauthorization");
                }
                return _oauth_clientauthorization;
            }
        }
        private ObjectSet<oauth_clientauthorization> _oauth_clientauthorization;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<oauth_nonce> oauth_nonce
        {
            get
            {
                if ((_oauth_nonce == null))
                {
                    _oauth_nonce = base.CreateObjectSet<oauth_nonce>("oauth_nonce");
                }
                return _oauth_nonce;
            }
        }
        private ObjectSet<oauth_nonce> _oauth_nonce;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<oauth_symmetriccryptokey> oauth_symmetriccryptokey
        {
            get
            {
                if ((_oauth_symmetriccryptokey == null))
                {
                    _oauth_symmetriccryptokey = base.CreateObjectSet<oauth_symmetriccryptokey>("oauth_symmetriccryptokey");
                }
                return _oauth_symmetriccryptokey;
            }
        }
        private ObjectSet<oauth_symmetriccryptokey> _oauth_symmetriccryptokey;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<sys_user> sys_user
        {
            get
            {
                if ((_sys_user == null))
                {
                    _sys_user = base.CreateObjectSet<sys_user>("sys_user");
                }
                return _sys_user;
            }
        }
        private ObjectSet<sys_user> _sys_user;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<op_group> op_group
        {
            get
            {
                if ((_op_group == null))
                {
                    _op_group = base.CreateObjectSet<op_group>("op_group");
                }
                return _op_group;
            }
        }
        private ObjectSet<op_group> _op_group;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 oauth_client EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTooauth_client(oauth_client oauth_client)
        {
            base.AddObject("oauth_client", oauth_client);
        }
    
        /// <summary>
        /// 用于向 oauth_clientauthorization EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTooauth_clientauthorization(oauth_clientauthorization oauth_clientauthorization)
        {
            base.AddObject("oauth_clientauthorization", oauth_clientauthorization);
        }
    
        /// <summary>
        /// 用于向 oauth_nonce EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTooauth_nonce(oauth_nonce oauth_nonce)
        {
            base.AddObject("oauth_nonce", oauth_nonce);
        }
    
        /// <summary>
        /// 用于向 oauth_symmetriccryptokey EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTooauth_symmetriccryptokey(oauth_symmetriccryptokey oauth_symmetriccryptokey)
        {
            base.AddObject("oauth_symmetriccryptokey", oauth_symmetriccryptokey);
        }
    
        /// <summary>
        /// 用于向 sys_user EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTosys_user(sys_user sys_user)
        {
            base.AddObject("sys_user", sys_user);
        }
    
        /// <summary>
        /// 用于向 op_group EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToop_group(op_group op_group)
        {
            base.AddObject("op_group", op_group);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAuthModel", Name="oauth_client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class oauth_client : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 oauth_client 对象。
        /// </summary>
        /// <param name="clientId">ClientId 属性的初始值。</param>
        /// <param name="clientIdentifier">ClientIdentifier 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="clientType">ClientType 属性的初始值。</param>
        public static oauth_client Createoauth_client(global::System.Int32 clientId, global::System.String clientIdentifier, global::System.String name, global::System.Int32 clientType)
        {
            oauth_client oauth_client = new oauth_client();
            oauth_client.ClientId = clientId;
            oauth_client.ClientIdentifier = clientIdentifier;
            oauth_client.Name = name;
            oauth_client.ClientType = clientType;
            return oauth_client;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    OnClientIdChanging(value);
                    ReportPropertyChanging("ClientId");
                    _ClientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClientId");
                    OnClientIdChanged();
                }
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientIdentifier
        {
            get
            {
                return _ClientIdentifier;
            }
            set
            {
                OnClientIdentifierChanging(value);
                ReportPropertyChanging("ClientIdentifier");
                _ClientIdentifier = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClientIdentifier");
                OnClientIdentifierChanged();
            }
        }
        private global::System.String _ClientIdentifier;
        partial void OnClientIdentifierChanging(global::System.String value);
        partial void OnClientIdentifierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientSecret
        {
            get
            {
                return _ClientSecret;
            }
            set
            {
                OnClientSecretChanging(value);
                ReportPropertyChanging("ClientSecret");
                _ClientSecret = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientSecret");
                OnClientSecretChanged();
            }
        }
        private global::System.String _ClientSecret;
        partial void OnClientSecretChanging(global::System.String value);
        partial void OnClientSecretChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Callback
        {
            get
            {
                return _Callback;
            }
            set
            {
                OnCallbackChanging(value);
                ReportPropertyChanging("Callback");
                _Callback = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Callback");
                OnCallbackChanged();
            }
        }
        private global::System.String _Callback;
        partial void OnCallbackChanging(global::System.String value);
        partial void OnCallbackChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientType
        {
            get
            {
                return _ClientType;
            }
            set
            {
                OnClientTypeChanging(value);
                ReportPropertyChanging("ClientType");
                _ClientType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientType");
                OnClientTypeChanged();
            }
        }
        private global::System.Int32 _ClientType;
        partial void OnClientTypeChanging(global::System.Int32 value);
        partial void OnClientTypeChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAuthModel", "Client_ClientAuthorization", "oauth_clientauthorization")]
        public EntityCollection<oauth_clientauthorization> oauth_clientauthorization
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<oauth_clientauthorization>("OAuthModel.Client_ClientAuthorization", "oauth_clientauthorization");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<oauth_clientauthorization>("OAuthModel.Client_ClientAuthorization", "oauth_clientauthorization", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAuthModel", Name="oauth_clientauthorization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class oauth_clientauthorization : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 oauth_clientauthorization 对象。
        /// </summary>
        /// <param name="authorizationId">AuthorizationId 属性的初始值。</param>
        /// <param name="createdOnUtc">CreatedOnUtc 属性的初始值。</param>
        /// <param name="clientId">ClientId 属性的初始值。</param>
        public static oauth_clientauthorization Createoauth_clientauthorization(global::System.Int32 authorizationId, global::System.DateTime createdOnUtc, global::System.Int32 clientId)
        {
            oauth_clientauthorization oauth_clientauthorization = new oauth_clientauthorization();
            oauth_clientauthorization.AuthorizationId = authorizationId;
            oauth_clientauthorization.CreatedOnUtc = createdOnUtc;
            oauth_clientauthorization.ClientId = clientId;
            return oauth_clientauthorization;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthorizationId
        {
            get
            {
                return _AuthorizationId;
            }
            set
            {
                if (_AuthorizationId != value)
                {
                    OnAuthorizationIdChanging(value);
                    ReportPropertyChanging("AuthorizationId");
                    _AuthorizationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AuthorizationId");
                    OnAuthorizationIdChanged();
                }
            }
        }
        private global::System.Int32 _AuthorizationId;
        partial void OnAuthorizationIdChanging(global::System.Int32 value);
        partial void OnAuthorizationIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOnUtc
        {
            get
            {
                return _CreatedOnUtc;
            }
            set
            {
                OnCreatedOnUtcChanging(value);
                ReportPropertyChanging("CreatedOnUtc");
                _CreatedOnUtc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOnUtc");
                OnCreatedOnUtcChanged();
            }
        }
        private global::System.DateTime _CreatedOnUtc;
        partial void OnCreatedOnUtcChanging(global::System.DateTime value);
        partial void OnCreatedOnUtcChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Scope
        {
            get
            {
                return _Scope;
            }
            set
            {
                OnScopeChanging(value);
                ReportPropertyChanging("Scope");
                _Scope = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Scope");
                OnScopeChanged();
            }
        }
        private global::System.String _Scope;
        partial void OnScopeChanging(global::System.String value);
        partial void OnScopeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpirationDateUtc
        {
            get
            {
                return _ExpirationDateUtc;
            }
            set
            {
                OnExpirationDateUtcChanging(value);
                ReportPropertyChanging("ExpirationDateUtc");
                _ExpirationDateUtc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDateUtc");
                OnExpirationDateUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpirationDateUtc;
        partial void OnExpirationDateUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnExpirationDateUtcChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAuthModel", "Client_ClientAuthorization", "oauth_client")]
        public oauth_client oauth_client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<oauth_client>("OAuthModel.Client_ClientAuthorization", "oauth_client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<oauth_client>("OAuthModel.Client_ClientAuthorization", "oauth_client").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<oauth_client> oauth_clientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<oauth_client>("OAuthModel.Client_ClientAuthorization", "oauth_client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<oauth_client>("OAuthModel.Client_ClientAuthorization", "oauth_client", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAuthModel", "User_ClientAuthorization", "sys_user")]
        public sys_user sys_user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sys_user>("OAuthModel.User_ClientAuthorization", "sys_user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sys_user>("OAuthModel.User_ClientAuthorization", "sys_user").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<sys_user> sys_userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<sys_user>("OAuthModel.User_ClientAuthorization", "sys_user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<sys_user>("OAuthModel.User_ClientAuthorization", "sys_user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAuthModel", Name="oauth_nonce")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class oauth_nonce : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 oauth_nonce 对象。
        /// </summary>
        /// <param name="context">Context 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="timestamp">Timestamp 属性的初始值。</param>
        public static oauth_nonce Createoauth_nonce(global::System.String context, global::System.String code, global::System.DateTime timestamp)
        {
            oauth_nonce oauth_nonce = new oauth_nonce();
            oauth_nonce.Context = context;
            oauth_nonce.Code = code;
            oauth_nonce.Timestamp = timestamp;
            return oauth_nonce;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Context
        {
            get
            {
                return _Context;
            }
            set
            {
                if (_Context != value)
                {
                    OnContextChanging(value);
                    ReportPropertyChanging("Context");
                    _Context = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Context");
                    OnContextChanged();
                }
            }
        }
        private global::System.String _Context;
        partial void OnContextChanging(global::System.String value);
        partial void OnContextChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                if (_Timestamp != value)
                {
                    OnTimestampChanging(value);
                    ReportPropertyChanging("Timestamp");
                    _Timestamp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Timestamp");
                    OnTimestampChanged();
                }
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAuthModel", Name="oauth_symmetriccryptokey")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class oauth_symmetriccryptokey : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 oauth_symmetriccryptokey 对象。
        /// </summary>
        /// <param name="bucket">Bucket 属性的初始值。</param>
        /// <param name="handle">Handle 属性的初始值。</param>
        /// <param name="expiresUtc">ExpiresUtc 属性的初始值。</param>
        /// <param name="secret">Secret 属性的初始值。</param>
        public static oauth_symmetriccryptokey Createoauth_symmetriccryptokey(global::System.String bucket, global::System.String handle, global::System.DateTime expiresUtc, global::System.Byte[] secret)
        {
            oauth_symmetriccryptokey oauth_symmetriccryptokey = new oauth_symmetriccryptokey();
            oauth_symmetriccryptokey.Bucket = bucket;
            oauth_symmetriccryptokey.Handle = handle;
            oauth_symmetriccryptokey.ExpiresUtc = expiresUtc;
            oauth_symmetriccryptokey.Secret = secret;
            return oauth_symmetriccryptokey;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bucket
        {
            get
            {
                return _Bucket;
            }
            set
            {
                if (_Bucket != value)
                {
                    OnBucketChanging(value);
                    ReportPropertyChanging("Bucket");
                    _Bucket = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Bucket");
                    OnBucketChanged();
                }
            }
        }
        private global::System.String _Bucket;
        partial void OnBucketChanging(global::System.String value);
        partial void OnBucketChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.String _Handle;
        partial void OnHandleChanging(global::System.String value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpiresUtc
        {
            get
            {
                return _ExpiresUtc;
            }
            set
            {
                OnExpiresUtcChanging(value);
                ReportPropertyChanging("ExpiresUtc");
                _ExpiresUtc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpiresUtc");
                OnExpiresUtcChanged();
            }
        }
        private global::System.DateTime _ExpiresUtc;
        partial void OnExpiresUtcChanging(global::System.DateTime value);
        partial void OnExpiresUtcChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Secret
        {
            get
            {
                return StructuralObject.GetValidValue(_Secret);
            }
            set
            {
                OnSecretChanging(value);
                ReportPropertyChanging("Secret");
                _Secret = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Secret");
                OnSecretChanged();
            }
        }
        private global::System.Byte[] _Secret;
        partial void OnSecretChanging(global::System.Byte[] value);
        partial void OnSecretChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAuthModel", Name="op_group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class op_group : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 op_group 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="config">Config 属性的初始值。</param>
        /// <param name="defaultAdmin">DefaultAdmin 属性的初始值。</param>
        /// <param name="createUser">CreateUser 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="editUser">EditUser 属性的初始值。</param>
        /// <param name="editTime">EditTime 属性的初始值。</param>
        public static op_group Createop_group(global::System.Int32 id, global::System.String code, global::System.String name, global::System.String config, global::System.String defaultAdmin, global::System.String createUser, global::System.DateTime createTime, global::System.String editUser, global::System.DateTime editTime)
        {
            op_group op_group = new op_group();
            op_group.ID = id;
            op_group.Code = code;
            op_group.Name = name;
            op_group.Config = config;
            op_group.DefaultAdmin = defaultAdmin;
            op_group.CreateUser = createUser;
            op_group.CreateTime = createTime;
            op_group.EditUser = editUser;
            op_group.EditTime = editTime;
            return op_group;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Config
        {
            get
            {
                return _Config;
            }
            set
            {
                OnConfigChanging(value);
                ReportPropertyChanging("Config");
                _Config = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Config");
                OnConfigChanged();
            }
        }
        private global::System.String _Config;
        partial void OnConfigChanging(global::System.String value);
        partial void OnConfigChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DefaultAdmin
        {
            get
            {
                return _DefaultAdmin;
            }
            set
            {
                OnDefaultAdminChanging(value);
                ReportPropertyChanging("DefaultAdmin");
                _DefaultAdmin = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DefaultAdmin");
                OnDefaultAdminChanged();
            }
        }
        private global::System.String _DefaultAdmin;
        partial void OnDefaultAdminChanging(global::System.String value);
        partial void OnDefaultAdminChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.String _CreateUser;
        partial void OnCreateUserChanging(global::System.String value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EditUser
        {
            get
            {
                return _EditUser;
            }
            set
            {
                OnEditUserChanging(value);
                ReportPropertyChanging("EditUser");
                _EditUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EditUser");
                OnEditUserChanged();
            }
        }
        private global::System.String _EditUser;
        partial void OnEditUserChanging(global::System.String value);
        partial void OnEditUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EditTime
        {
            get
            {
                return _EditTime;
            }
            set
            {
                OnEditTimeChanging(value);
                ReportPropertyChanging("EditTime");
                _EditTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditTime");
                OnEditTimeChanged();
            }
        }
        private global::System.DateTime _EditTime;
        partial void OnEditTimeChanging(global::System.DateTime value);
        partial void OnEditTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OAuthModel", Name="sys_user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sys_user : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 sys_user 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="username">Username 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="fullName">FullName 属性的初始值。</param>
        /// <param name="email">Email 属性的初始值。</param>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        /// <param name="createUser">CreateUser 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static sys_user Createsys_user(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String fullName, global::System.String email, global::System.Int32 roleID, global::System.Int32 createUser, global::System.DateTime createTime, global::System.Boolean status)
        {
            sys_user sys_user = new sys_user();
            sys_user.ID = id;
            sys_user.Username = username;
            sys_user.Password = password;
            sys_user.FullName = fullName;
            sys_user.Email = email;
            sys_user.RoleID = roleID;
            sys_user.CreateUser = createUser;
            sys_user.CreateTime = createTime;
            sys_user.Status = status;
            return sys_user;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HeadUrl
        {
            get
            {
                return _HeadUrl;
            }
            set
            {
                OnHeadUrlChanging(value);
                ReportPropertyChanging("HeadUrl");
                _HeadUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HeadUrl");
                OnHeadUrlChanged();
            }
        }
        private global::System.String _HeadUrl;
        partial void OnHeadUrlChanging(global::System.String value);
        partial void OnHeadUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GroupID;
        partial void OnGroupIDChanging(Nullable<global::System.Int32> value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreateUser
        {
            get
            {
                return _CreateUser;
            }
            set
            {
                OnCreateUserChanging(value);
                ReportPropertyChanging("CreateUser");
                _CreateUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUser");
                OnCreateUserChanged();
            }
        }
        private global::System.Int32 _CreateUser;
        partial void OnCreateUserChanging(global::System.Int32 value);
        partial void OnCreateUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Boolean _Status;
        partial void OnStatusChanging(global::System.Boolean value);
        partial void OnStatusChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OAuthModel", "User_ClientAuthorization", "oauth_clientauthorization")]
        public EntityCollection<oauth_clientauthorization> oauth_clientauthorization
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<oauth_clientauthorization>("OAuthModel.User_ClientAuthorization", "oauth_clientauthorization");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<oauth_clientauthorization>("OAuthModel.User_ClientAuthorization", "oauth_clientauthorization", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
